name: Test ref-farming
on: [push]
  #  push:
  #    branches: [ master ]
  #  pull_request:
  #    branches: [ master ]
jobs:
  test_ref_farming:
    runs-on: ubuntu-latest 
    container:
      image: nearprotocol/contract-builder:latest
      env:
        RUSTFLAGS: -C link-arg=-s
    steps:
      - uses: actions/checkout@v2
      - run: |
          rustup toolchain install stable-2020-10-08 && \
          rustup default stable-2020-10-08 && \
          rustup target add wasm32-unknown-unknown && \
          cargo build --target wasm32-unknown-unknown --release
      - run: |
          cd ref-exchange && \
          cargo test
